### ISSUE TITLE
JRE Version needed?

### ISSUE THREAD

**Issue by olivergrimm** [GeoWerkstatt/interlis-testbed-runner#6]
Mit Java 1.8.0_391 erhalte ich die Meldung
```compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 52.0```

Mit JRE 21 dann:
```
Fehler: Hauptklasse ch.geowerkstatt.interlis.testbed.runner.Main kann nicht initialisiert werden
Ursache: java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
```
Welche Runtime Version ist zu verwenden? Oder mache ich etwas falsch? Mein Call ist:

`java -jar .\_Runner\interlis-testbed-runner-0.0.1-SNAPSHOT.jar --validator "C:\Program Files\INTERLIS\ilivalidator\ilivalidator-1.14.2-SNAPSHOT.jar" .\TestSuite-1`

**Comment by domi-b** [comment]
Die JRE Version 21 ist richtig, allerdings fehlen die benötigten Abhängigkeiten (log4j und Apache Commons CLI).
Die jar-Dateien von `commons-cli`, `log4j-api` und `log4j-core` sollten dafür im gleichen Ordner wie die `interlis-testbed-runner`-jar sein.

**Comment by domi-b** [comment]
In den Assets bei den [Github Releases](https://github.com/GeoWerkstatt/interlis-testbed-runner/releases) ist nun jeweils eine Zip-Datei mit dem ausführbaren Testbed-Runner und den benötigten Abhängigkeiten verfügbar.
